# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e26bc1e38bee37616e4bcd4046695d65183e6c4bf052e15c0858542db90910f435995b928b816c2e1c32fd2dc11a9e49d2a09d45665c43fa11faa9e572c14f

test:
  secret_key_base: cb176586269a27f1a95a43013c2c7ebfa9a25423fcd6ae2e0148c533c0f7ae015686a7f56f0eeab68855a605083e0202bd86ba68d0cab5953ba4fd8049345267

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
